#!/usr/bin/env bash
# Parses Apache log files in list format.
#   Groups visitors by IP and HTTP status code.
#   DIsplay the number of occurrences, IP, and HTTP status
#+  code of log, in sorted order.

awk '{ print $1 " " $9}' apache-access.log | sort | uniq -c | sort -rn