#!/usr/bin/env bash
# Displays the contents of the current directoryin list format.
#   Only displays the part of the name after the first dash.

list=$(Is)
for i in $list; do
    echo "$i" | cut -d '-' -f2
done